name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build_n_push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get the tag name
      run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
    - name: Test
      run: |
        echo $TAG
        echo ${{ env.TAG }}

    #- name: Build the Docker image
    #  run: docker build . --file Dockerfile --tag brahama/algo/indexer:$(git describe |cut -d '-' -f 1)
    #- name: DockerHub Login
    #  uses: docker/login-action@v1 
    #  with:
    #    username: ${{ secrets.DOCKERHUB_USERNAME }}
    #    password: ${{ secrets.DOCKERHUB_TOKEN }}
    #- name: Docker Push
    #  run: docker push brahama/algo/indexer:$(git describe |cut -d '-' -f 1)
      
