name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build_n_push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup git config
      run: |
        # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git fetch --tags

    - name: Git Describe
      run: |
        git describe

    #- name: Build the Docker image
    #  run: docker build . --file Dockerfile --tag brahama/algo/indexer:$(git describe |cut -d '-' -f 1)
    #- name: DockerHub Login
    #  uses: docker/login-action@v1 
    #  with:
    #    username: ${{ secrets.DOCKERHUB_USERNAME }}
    #    password: ${{ secrets.DOCKERHUB_TOKEN }}
    #- name: Docker Push
    #  run: docker push brahama/algo/indexer:$(git describe |cut -d '-' -f 1)
      
